version: "2.4"

services:
  sut:
    build: .
    image: localhost:5000/sut
    privileged: true
    tmpfs:
      - /tmp
      - /run
      - /var/run
    tty: true
    volumes:
      - data:/var/lib/firecracker-containerd
    environment:
      FICD_IMAGE_TAG: docker.io/library/hello-world:latest
      FICD_KEEP_ALIVE: false
