version: "2.4"

services:
  firecracker:
    build: .
    privileged: true
    tmpfs:
      - /tmp
    volumes:
      - files:/files
    labels:
      io.balena.features.balena-socket: 1

volumes:
  files: {}
