version: "2.4"

services:
  firecracker:
    build: .
    privileged: true
    tmpfs:
      - /tmp
      - /run
      - /var/run
    tty: true
    volumes:
      - data:/var/lib/firecracker-containerd

volumes:
  data: {}