version: "2.4"

services:
  firecracker:
    build: .
    # Privileged is required to setup the rootfs and jailer
    # but permissions are dropped to a chroot in order to start your VM
    privileged: true
    network_mode: host
    # Optionally run the VM rootfs and kernel in-memory to save storage wear
    tmpfs:
      - /tmp
      - /run
      - /srv
    volumes:
      - persistent-data:/jail/data

volumes:
  persistent-data: {}
  