# https://github.com/zyedidia/eget#configuration
[global]
quiet = false
show_hash = true
upgrade_only = false
all = true

["firecracker-microvm/firecracker"]
asset_filters = ["x86_64.tgz", "^sha256"]
verify_sha256 = "55f4e8dd3693aaa0584f6fc2656d05e6d197693e02c8170a0673f95ea73504b2"
file = "**/*-x86_64"
target = "/usr/local/bin"
