#!/bin/sh

exec 1>/dev/console
exec 2>/dev/console

# Mount essential file systems
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

# Mount tmpfs
mount -o remount,rw,exec tmpfs /tmp
mount -o remount,rw,exec tmpfs /var/run

# Bring up networking
# https://github.com/firecracker-microvm/firecracker/blob/main/resources/overlay/usr/local/bin/fcnet-setup.sh
/usr/local/bin/fcnet-setup.sh

# Export secrets to the environment and remove the files
for f in /var/secrets/*; do
    eval "export $(basename "${f}")=$(cat "${f}")"
    rm -f "${f}"
done
