# https://github.com/zyedidia/eget#configuration
[global]
quiet = false
show_hash = true
upgrade_only = false
all = true

["firecracker-microvm/firecracker"]
asset_filters = ["aarch64.tgz", "^sha256"]
verify_sha256 = "3832016b8f365fc6cd851caf7662061a2ffa0596227f4d9c7fcb4059845c2369"
file = "**/*-aarch64"
target = "/usr/local/bin"
